[layout]
name = "WinGame-Default"
opacity = 0.5

[buttons.a]
mapping = "KEY_ENTER"
position = { x = 85, y = 80 }
size = 60

[buttons.b]
mapping = "KEY_ESC"
position = { x = 92, y = 70 }
size = 60

[joystick.left]
type = "analog"
mapping = "WASD"
position = { x = 15, y = 75 }
